using System;
using System.Collections.Generic;
using System.Xml;

using MiKoSolutions.SemanticParsers.Xml.Yaml;

namespace MiKoSolutions.SemanticParsers.Xml.Flavors
{
    public sealed class XmlFlavorForWix : XmlFlavor
    {
        private static readonly HashSet<string> TerminalNodeNames = new HashSet<string>
                                                                        {
                                                                            "ApprovedExeForElevation",
                                                                            "AllocateRegistrySpace",
                                                                            "AppSearch",
                                                                            "AssemblyName",
                                                                            "BinaryRef",
                                                                            "BindImage",
                                                                            "Catalog",
                                                                            "CCPSearch",
                                                                            "Column",
                                                                            "CommandLine",
                                                                            "ComponentGroupRef",
                                                                            "ComponentRef",
                                                                            "Condition",
                                                                            "Configuration",
                                                                            "ConfigurationData",
                                                                            "ContainerRef",
                                                                            "CopyFile",
                                                                            "CostFinalize",
                                                                            "CostInitialize",
                                                                            "CreateFolders",
                                                                            "CreateShortcuts",
                                                                            "Custom",
                                                                            "CustomAction",
                                                                            "CustomActionRef",
                                                                            "CustomProperty",
                                                                            "Data",
                                                                            "DeleteServices",
                                                                            "Dependency",
                                                                            "DialogRef",
                                                                            "DigitalCertificate",
                                                                            "DigitalCertificateRef",
                                                                            "DisableRollback",
                                                                            "DuplicateFiles",
                                                                            "EmbeddedChainer",
                                                                            "EmbeddedChainerRef",
                                                                            "EmbeddedUIResource",
                                                                            "EnsureTable",
                                                                            "Environment",
                                                                            "Error",
                                                                            "Exclusion",
                                                                            "ExecuteAction",
                                                                            "ExitCode",
                                                                            "Failure",
                                                                            "FeatureGroupRef",
                                                                            "File", // This is not a real terminal node but we consider it to be one as it's about a single file
                                                                            "FileCost",
                                                                            "FileSearch",
                                                                            "FileSearchRef",
                                                                            "FileTypeMask",
                                                                            "FindRelatedProducts",
                                                                            "ForceReboot",
                                                                            "Icon",
                                                                            "IconRef",
                                                                            "IgnoreModularization",
                                                                            "IgnoreRange",
                                                                            "IgnoreTable",
                                                                            "IniFile",
                                                                            "InstallAdminPackage",
                                                                            "InstallExecute",
                                                                            "InstallExecuteAgain",
                                                                            "InstallFiles",
                                                                            "InstallFinalize",
                                                                            "InstallInitialize",
                                                                            "InstallODBC",
                                                                            "InstallServices",
                                                                            "InstallValidate",
                                                                            "Instance",
                                                                            "Interface",
                                                                            "IsolateComponent",
                                                                            "IsolateComponents",
                                                                            "LaunchConditions",
                                                                            "ListItem",
                                                                            "Log",
                                                                            "MajorUpgrade",
                                                                            "MediaTemplate",
                                                                            "MergeRef",
                                                                            "MigrateFeatureStates",
                                                                            "MIME",
                                                                            "MoveFiles",
                                                                            "MsiProperty",
                                                                            "MsiPublishAssemblies",
                                                                            "MsiUnpublishAssemblies",
                                                                            "MultiStringValue",
                                                                            "ODBCTranslator",
                                                                            "OptimizeCustomActions",
                                                                            "OptionalUpdateRegistration",
                                                                            "Package",
                                                                            "PackageGroupRef",
                                                                            "PatchFamilyGroupRef",
                                                                            "PatchFamilyRef",
                                                                            "PatchFiles",
                                                                            "PatchInformation",
                                                                            "PatchProperty",
                                                                            "PatchSequence",
                                                                            "Payload",
                                                                            "PayloadGroupRef",
                                                                            "Permission",
                                                                            "ProcessComponents",
                                                                            "ProductSearch",
                                                                            "ProgressText",
                                                                            "PropertyRef",
                                                                            "ProtectRange",
                                                                            "Publish",
                                                                            "PublishComponents",
                                                                            "PublishFeatures",
                                                                            "PublishProduct",
                                                                            "RadioButton",
                                                                            "RegisterClassInfo",
                                                                            "RegisterComPlus",
                                                                            "RegisterExtensionInfo",
                                                                            "RegisterFonts",
                                                                            "RegisterMIMEInfo",
                                                                            "RegisterProduct",
                                                                            "RegisterProgIdInfo",
                                                                            "RegisterTypeLibraries",
                                                                            "RegisterUser",
                                                                            "RegistrySearch", // This is not a real terminal node but we consider it to be one as it's about a single search in the registry
                                                                            "RegistrySearchRef",
                                                                            "RegistryValue", // This is not a real terminal node but we consider it to be one as it's about a single entry in the registry
                                                                            "RelatedBundle",
                                                                            "RemotePayload",
                                                                            "RemoveDuplicateFiles",
                                                                            "RemoveEnvironmentStrings",
                                                                            "RemoveExistingProducts",
                                                                            "RemoveFile",
                                                                            "RemoveFiles",
                                                                            "RemoveFolder",
                                                                            "RemoveFolders",
                                                                            "RemoveIniValues",
                                                                            "RemoveODBC",
                                                                            "RemoveRegistryKey",
                                                                            "RemoveRegistryValue",
                                                                            "RemoveRegistryValues",
                                                                            "RemoveShortcuts",
                                                                            "ReplacePatch",
                                                                            "RequiredPrivilege",
                                                                            "ReserveCost",
                                                                            "ResolveSource",
                                                                            "RMCCPSearch",
                                                                            "ScheduleReboot",
                                                                            "SelfRegModules",
                                                                            "SelfUnregModules",
                                                                            "ServiceArgument",
                                                                            "ServiceDependency",
                                                                            "SetDirectory",
                                                                            "SetODBCFolders",
                                                                            "SetProperty",
                                                                            "SFPFile",
                                                                            "Shortcut", // This is not a real terminal node but we consider it to be one as it's about a single shortcut
                                                                            "ShortcutProperty",
                                                                            "Show",
                                                                            "SlipstreamMsp",
                                                                            "StartServices",
                                                                            "StopServices",
                                                                            "Subscribe",
                                                                            "Substitution",
                                                                            "SymbolPath",
                                                                            "TargetProductCode",
                                                                            "Text",
                                                                            "TextStyle",
                                                                            "UIRef",
                                                                            "UIText",
                                                                            "UnpublishComponents",
                                                                            "UnpublishFeatures",
                                                                            "UnregisterClassInfo",
                                                                            "UnregisterComPlus",
                                                                            "UnregisterExtensionInfo",
                                                                            "UnregisterFonts",
                                                                            "UnregisterMIMEInfo",
                                                                            "UnregisterProgIdInfo",
                                                                            "UnregisterTypeLibraries",
                                                                            "Update",
                                                                            "UpgradeVersion",
                                                                            "Validate",
                                                                            "ValidateProductID",
                                                                            "Variable",
                                                                            "Verb",
                                                                            "WixVariable",
                                                                            "WriteEnvironmentStrings",
                                                                            "WriteIniValues",
                                                                            "WriteRegistryValues",
                                                                        };

        public override bool ParseAttributesEnabled => false;

        public override bool Supports(string filePath) => filePath.EndsWith(".wxs", StringComparison.OrdinalIgnoreCase);

        public override bool Supports(DocumentInfo info) => string.Equals(info.RootElement, "Wix", StringComparison.OrdinalIgnoreCase);

        public override string GetName(XmlTextReader reader)
        {
            if (reader.NodeType == XmlNodeType.Element)
            {
                var name = reader.Name;
                var identifier = reader.GetAttribute("Name") ?? reader.GetAttribute("Key") ?? reader.GetAttribute("Id") ?? reader.GetAttribute("Action");
                return identifier ?? name;
            }

            return base.GetName(reader);
        }

        public override string GetType(XmlTextReader reader) => reader.NodeType == XmlNodeType.Element ? reader.Name : base.GetType(reader);

        protected override bool ShallBeTerminalNode(ContainerOrTerminalNode node) => TerminalNodeNames.Contains(node?.Type);
    }
}