# https://docs.codecov.io/docs/codecov-yaml
# https://github.com/codecov/support/wiki/Codecov-Yaml

coverage:
  range: 70..100
  round: down
  precision: 2
  
ignore:
      - Tests/

coverage:
  status:
    project:
      default: off
      api:
        target: 100%
        flags: api

flags:
  api:
    paths:
      - Parser/
  test:
    paths:
      - Tests/

codecov:
  token: TOKEN_HERE